name: prms_app
description: Property Rental Management System - PRMS

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  intl: ^0.19.0
  fl_chart: ^0.68.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  flutter_animate: ^4.5.0
  lottie: ^3.1.0
  image_picker: ^1.1.1
  url_launcher: ^6.2.6
  fluttertoast: ^8.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
